/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardSubmitRouteImport } from './routes/dashboard.submit'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminIncomingRouteImport } from './routes/admin.incoming'
import { Route as AdminBuilderRouteImport } from './routes/admin.builder'
import { Route as AdminIncomingIndexRouteImport } from './routes/admin.incoming.index'
import { Route as AdminIncomingIdRouteImport } from './routes/admin.incoming.$id'
import { Route as NewspaperYearMonthDayRouteImport } from './routes/newspaper.$year.$month.$day'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardSubmitRoute = DashboardSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncomingRoute = AdminIncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuilderRoute = AdminBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncomingIndexRoute = AdminIncomingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminIncomingRoute,
} as any)
const AdminIncomingIdRoute = AdminIncomingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminIncomingRoute,
} as any)
const NewspaperYearMonthDayRoute = NewspaperYearMonthDayRouteImport.update({
  id: '/newspaper/$year/$month/$day',
  path: '/newspaper/$year/$month/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/incoming': typeof AdminIncomingRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/incoming/$id': typeof AdminIncomingIdRoute
  '/admin/incoming/': typeof AdminIncomingIndexRoute
  '/newspaper/$year/$month/$day': typeof NewspaperYearMonthDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/incoming/$id': typeof AdminIncomingIdRoute
  '/admin/incoming': typeof AdminIncomingIndexRoute
  '/newspaper/$year/$month/$day': typeof NewspaperYearMonthDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/incoming': typeof AdminIncomingRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/submit': typeof DashboardSubmitRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/incoming/$id': typeof AdminIncomingIdRoute
  '/admin/incoming/': typeof AdminIncomingIndexRoute
  '/newspaper/$year/$month/$day': typeof NewspaperYearMonthDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/admin/builder'
    | '/admin/incoming'
    | '/admin/settings'
    | '/admin/templates'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/submit'
    | '/admin/'
    | '/dashboard/'
    | '/admin/incoming/$id'
    | '/admin/incoming/'
    | '/newspaper/$year/$month/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/builder'
    | '/admin/settings'
    | '/admin/templates'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/submit'
    | '/admin'
    | '/dashboard'
    | '/admin/incoming/$id'
    | '/admin/incoming'
    | '/newspaper/$year/$month/$day'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/admin/builder'
    | '/admin/incoming'
    | '/admin/settings'
    | '/admin/templates'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/submit'
    | '/admin/'
    | '/dashboard/'
    | '/admin/incoming/$id'
    | '/admin/incoming/'
    | '/newspaper/$year/$month/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  NewspaperYearMonthDayRoute: typeof NewspaperYearMonthDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/submit': {
      id: '/dashboard/submit'
      path: '/submit'
      fullPath: '/dashboard/submit'
      preLoaderRoute: typeof DashboardSubmitRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incoming': {
      id: '/admin/incoming'
      path: '/incoming'
      fullPath: '/admin/incoming'
      preLoaderRoute: typeof AdminIncomingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/builder': {
      id: '/admin/builder'
      path: '/builder'
      fullPath: '/admin/builder'
      preLoaderRoute: typeof AdminBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incoming/': {
      id: '/admin/incoming/'
      path: '/'
      fullPath: '/admin/incoming/'
      preLoaderRoute: typeof AdminIncomingIndexRouteImport
      parentRoute: typeof AdminIncomingRoute
    }
    '/admin/incoming/$id': {
      id: '/admin/incoming/$id'
      path: '/$id'
      fullPath: '/admin/incoming/$id'
      preLoaderRoute: typeof AdminIncomingIdRouteImport
      parentRoute: typeof AdminIncomingRoute
    }
    '/newspaper/$year/$month/$day': {
      id: '/newspaper/$year/$month/$day'
      path: '/newspaper/$year/$month/$day'
      fullPath: '/newspaper/$year/$month/$day'
      preLoaderRoute: typeof NewspaperYearMonthDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminIncomingRouteChildren {
  AdminIncomingIdRoute: typeof AdminIncomingIdRoute
  AdminIncomingIndexRoute: typeof AdminIncomingIndexRoute
}

const AdminIncomingRouteChildren: AdminIncomingRouteChildren = {
  AdminIncomingIdRoute: AdminIncomingIdRoute,
  AdminIncomingIndexRoute: AdminIncomingIndexRoute,
}

const AdminIncomingRouteWithChildren = AdminIncomingRoute._addFileChildren(
  AdminIncomingRouteChildren,
)

interface AdminRouteChildren {
  AdminBuilderRoute: typeof AdminBuilderRoute
  AdminIncomingRoute: typeof AdminIncomingRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBuilderRoute: AdminBuilderRoute,
  AdminIncomingRoute: AdminIncomingRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubmitRoute: typeof DashboardSubmitRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubmitRoute: DashboardSubmitRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  NewspaperYearMonthDayRoute: NewspaperYearMonthDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
